### ISSUE TITLE
Implement Solidity binding rules

### ISSUE THREAD

**Issue by ggiraldez** [NomicFoundation/slang#1077]
This is an umbrella issue to track progress on the implementation and pending issues in binding rules for Solidity.

In progress or already started but on hold for now:

Completed:

- [x] Complete list of built-in types, global variables and functions #1125
- [x] Instantiate structs using named arguments #1125
- [x] Infrastructure for built-in units, types, variables and functions #1101
- [x] Contract constructors #1102
- [x] Contract getters for public state variables #1102
- [x] Support `this` scope #1102
- [x] Support modifiers inheritance and virtual lookup #1102
- [x] Interface inheritance #1102
- [x] Support for `using` ... `for` #1103
- [x] Add a perf test to measure/report constructing and querying bindings #1100
- [x] Contract inheritance #1075 
- [x] Resolution of virtual methods and multiple inheritance (C3 linearisation) #1075
- [x] Modifiers, fallback and receive functions #1090
- [x] Named arguments for function calls, events and custom errors #1090
- [x] Call options #1090
- [x] Ensure all expression nodes have an `.output` node connected to the type #1090
- [x] Inline Assembly #1087
- [x] Constants #1082
- [x] Arrays and mappings #1082
- [x] User-defined value types #1082
- [x] Function types #1082
- [x] Control statements (ie. if/else, for, while, etc)  #1076
- [X] Top-level definitions
- [X] Contracts, libraries and interface definitions
- [X] Imports
- [X] Function and arguments definitions
- [X] Basic expressions
- [X] Member access expressions
- [X] Blocks and statements
- [X] Variables and state variable declarations
- [X] Tuples and tuple deconstruction statements
- [X] Enums & Structs
- [X] Type expressions
