### ISSUE TITLE
Bindings API review and pending issues 

### ISSUE THREAD

**Issue by ggiraldez** [NomicFoundation/slang#1109]
We have some small pending tasks related to the Bindings API.

- [x] Make sure that any `Bindings` internal context/data is updated whenever a new file is added.
    - @OmarTawfik: assuming this has a perf impact, our latest v1 design can also make sure all files are loaded first THEN create Bindings once and for all, so we don't need to recalculate this multiple times.
- [x] (#1170) Document new graph attributes and their usage
- [x] (#1170) Move `lookup_definition_by_name` to the test modules
- [x] (#1170) Rename `jump_to_definition` to `resolve_definition` (or `resolve_reference`?)
    - @OmarTawfik: my 2c: I suggest `resolve_definition()` or `get_definition()`, as it is a function of the reference, which the user already has/already resolved. What is yet to be resolved/retrieved is the definition.
- [x] Cache pre-parsed bindings rules and built-ins per language version
- [x] (#1167) Output Mermaid and/or Graphviz .dot generated files under the target directory (rationale: they're only generated locally and for debugging purpose and are not tracked by Git, which may cause compilation failures when switching branches)
    - @OmarTawfik: assuming they have a perf impact on test execution, I suggest only generating them if a certain env variable was set, so that they don't affect us in 99% of the times the tests run...
- [x] Add a few tests to make sure bindings are still calculated successfully in the presence of syntax errors/partial input.
