### ISSUE TITLE
implement version breaking changes from in grammar

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#340]
This is a list of breaking changes mentioned in the official documentation. For each change, we need to make sure the versioning is implemented correctly in our grammar, and add tests to cover the parsed CST and errors reported before and after that version. Some changes like #351 likely need #182 to be implemented correctly.

Note: the docs below list the changes, but they are not necessarily released in the that exact version of the doc. To find out which actual version had the breaking change, I usually go to https://remix.ethereum.org/ and write a snippet there, and then do a manual binary search between the available compiler versions (dropdown) to find out which exact version started failing or succeeding.

### https://docs.soliditylang.org/en/v0.8.17/050-breaking-changes.html

#399

- [x] throw is now disallowed (in favor of revert, require and assert) - `0.5.0`.
- [x] The unit denomination years is now disallowed due to complications and confusions about leap years - `0.5.0`.
- [x] Trailing dots that are not followed by a number are now disallowed - `0.5.0`.
- [x] Combining hex numbers with unit denominations (e.g. 0x1e wei) is now disallowed - `0.5.0`.
- [x] The prefix 0X for hex numbers is disallowed, only 0x is possible - `0.5.0`.
- [x] The var keyword is now disallowed to favor explicitness - **Not a parse error until `0.7.0`**.
- [x] Using constant as function state mutability modifier is now disallowed- `0.5.0`.
- [x] The unary + operator is now disallowed - `0.5.0`.
- [x] New keywords: calldata and constructor - `0.5.0`.
- [x] New reserved keywords: alias, apply, auto, copyof, define, immutable, implements, macro, mutable, override, partial, promise, reference, sealed, sizeof, supports, typedef and unchecked - `0.5.0`.

### https://docs.soliditylang.org/en/v0.8.17/060-breaking-changes.html

- [x] The new keyword abstract can be used to mark contracts as abstract. It has to be used if a contract does not implement all its functions. Abstract contracts cannot be created using the new operator, and it is not possible to generate byte code for them during compilation - #397.
- [x] New: The try/catch statement allows you to react on failed external calls - #397.
- [x] Yul and Inline Assembly have a new statement called leave that exits the current function - #397.
- [x] #351

### https://docs.soliditylang.org/en/v0.8.17/070-breaking-changes.html

- [x] In external function and contract creation calls, Ether and gas is now specified using a new syntax: x.f{gas: 10000, value: 2 ether}(arg1, arg2). The old syntax – x.f.gas(10000).value(2 ether)(arg1, arg2) – will cause an error.
- [x] The global variable now is deprecated, block.timestamp should be used instead. The single identifier now is too generic for a global variable and could give the impression that it changes during transaction processing, whereas block.timestamp correctly reflects the fact that it is just a property of the block - **Not Syntactic**.
- [x] The token gwei is a keyword now (used to specify, e.g. 2 gwei as a number) and cannot be used as an identifier - `0.7.0`.
- [x] String literals now can only contain printable ASCII characters and this also includes a variety of escape sequences, such as hexadecimal (\xff) and unicode escapes (\u20ac).
- [x] Unicode string literals are supported now to accommodate valid UTF-8 sequences. They are identified with the unicode prefix: unicode"Hello 😃".
- [x] The finney and szabo denominations are removed. They are rarely used and do not make the actual amount readily visible. Instead, explicit values like 1e20 or the very common gwei can be used - `0.7.0` and later are valid identifiers.
- [x] The keyword var cannot be used anymore. Previously, this keyword would parse but result in a type error and a suggestion about which type to use. Now, it results in a parser error - `0.7.0` still reserved.

### https://docs.soliditylang.org/en/v0.8.17/080-breaking-changes.html

- [x] Arithmetic operations revert on underflow and overflow. You can use unchecked { ... } to use the previous wrapping behaviour - **Not Syntactic**.
- [x] Exponentiation is right associative, i.e., the expression a*\*b*\*c is parsed as a*\*(b*\*c). Before 0.8.0, it was parsed as (a*\*b)*\*c - `0.8.0`.
- [x] The type byte has been removed. It was an alias of bytes1 - `0.8.0` - #398.
- [x] Function call options can only be given once, i.e. c.f{gas: 10000}{value: 1}() is invalid and has to be changed to c.f{gas: 10000, value: 1}() - `0.8.0` - #398.

### https://blog.soliditylang.org/2023/02/22/user-defined-operators/

- [x] Support the new using syntax.
