### ISSUE TITLE
public API changes

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#640]
as discussed in #617:

- [x] Remove `ProductionKind` completely, since it is no longer needed. We only need to expose `fn parse(NonTerminalKind)`: #699
- [ ] Rename `TokenKind` to `TerminalKind`, since it will also refer to trivia. (#834)
- [ ] Rename `RuleKind` to `NonTerminalKind`, since "rule" is ambiguous. (#834)
- [ ] Remove `TerminalKind::SKIPPED` from `TerminalKind`, and add new `Node::Unrecognized(string)` and `Node::Missing(kind)` variants instead. (#835)
- [x] Hide `LexicalContext` and `fn scan(TokenKind)` from the public API: #728
- [x] Since `EndOFFileTrivia` no longer exists, `ParseResult` should collect any remaining trivia at the end of the input, and include it in the `ParseResult` returned, for any kind of non-terminal, not just `SourceUnit`.
- [ ] https://github.com/NomicFoundation/slang/issues/737

**Comment by Xanewok** [comment]
I've opened #834 and #835 to track the remaining work items that we should probably still discuss, so closing this umbrella issue; the Area in the project board serves to show that these are related to the public API, so there's no use tracking them in a group here.
