### ISSUE TITLE
perf benchmarking suite

### ISSUE THREAD

**Issue by OmarTawfik** [NomicFoundation/slang#808]
## Frameworks

- Cargo:
  - https://github.com/bheisler/iai
  - https://github.com/bheisler/criterion.rs
  - https://crates.io/crates/inferno
  - https://crates.io/crates/deepsize
- NPM:
  - https://www.npmjs.com/package/benchmark
  - https://www.npmjs.com/package/tinybench

## Todo

- [ ] Implement a few core user cases (examples below).
- [ ] Implement a script to run these tests locally and collect results across different commits: `infra measure test_name --ref $HASH1 --ref $HASH2 --ref $HASH3`.
- [ ] Measure CPU load, memory usage, and resulting binary/package size.
- [ ] Can we run in CI? report via [mermaid graphs](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-diagrams#creating-mermaid-diagrams)?

## Scenarios

1. Parsing files: small vs large contracts.
2. Parsing files: flat types vs nested expressions.
3. Using cursors to select specific kinds.
4. Using cursors to navigate up/down/around the tree.
5. Running queries E2E with/without captures.
6. Inspecting every node in the tree, which is critical for things like formatters, which will eventually need to access all of them.
